### ISSUE TITLE
MOTD Not shown / server appears offline.

### ISSUE THREAD

**Issue by thelucyclub** [ClearSkyTeam/ClearSky#444] opened 2016-05-04 11:12 UTC
Title.

**Comment by thelucyclub** [comment] 2016-05-04 11:13
Reproduce:
ping scpe.game-server.cc:19132
join scpe.game-server.cc:19132

**Comment by robske110** [comment] 2016-05-04 11:38
Duplicate of #444
Will fix this now

**Closed by robske110** 2016-05-04 11:38 UTC

**Comment by thelucyclub** [comment] 2016-05-04 23:23
Is it fixed yet? jw

**Comment by robske110** [comment] 2016-05-05 06:42
Yes

**Comment by Aericio** [comment] 2016-05-05 06:43
Thanks :D
