### ISSUE TITLE
MEM LEAK

### ISSUE THREAD

**Issue by starterdragon** [ClearSkyTeam/ClearSky#755] opened 2016-10-19 10:48 UTC
ClearSky Crash Dump Wed Oct 19 05:12:32 CDT 2016

Error: Allowed memory size of 2147483648 bytes exhausted (tried to allocate 4096 bytes)
File: /src/pocketmine/level/Level
Line: 1538
Type: E_ERROR

Code:
[1529] 
[1530] 		if($cached and isset($this->blockCache[$index])){
[1531] 			return $this->blockCache[$index];
[1532] 		}elseif($pos->y >= 0 and $pos->y < 128 and isset($this->chunks[$chunkIndex = Level::chunkHash($pos->x >> 4, $pos->z >> 4)])){
[1533] 			$fullState = $this->chunks[$chunkIndex]->getFullBlock($pos->x & 0x0f, $pos->y & 0x7f, $pos->z & 0x0f);
[1534] 		}else{
[1535] 			$fullState = 0;
[1536] 		}
[1537] 
[1538] 		$block = clone $this->blockStates[$fullState & 0xfff];
[1539] 
[1540] 		$block->x = $pos->x;
[1541] 		$block->y = $pos->y;
[1542] 		$block->z = $pos->z;
[1543] 		$block->level = $this;
[1544] 
[1545] 		array_push($this->blockCacheArray, $index);
[1546] 		return $this->blockCache[$index] = $block;
[1547] 	}
[1548] 

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

ClearSky version: 1.1 #451 [Protocol 83; API 2.0.0]
uname -a: Windows NT S19191748 6.1 build 7601 (Windows Server 2008 R2 Datacenter Edition Service Pack 1) AMD64
PHP Version: 7.0.9
Zend version: 3.0.0
OS : WINNT, win

**Comment by starterdragon** [comment] 2016-10-19 10:52
#724

**Comment by Aericio** [comment] 2016-10-20 02:33
Can you put the crashdump inside the ``s?
![image](https://cloud.githubusercontent.com/assets/16523741/19544314/bdee97c4-9619-11e6-8f87-2f5b877ecb5d.png)

**Comment by robske110** [comment] 2016-10-20 04:47
This is a duplicate of #724

**Closed by robske110** 2016-10-20 04:48 UTC
