### ISSUE TITLE
Can't eat bought items

### ISSUE THREAD

**Issue by ScandiePlay** [ClearSkyTeam/ClearSky#247] opened 2016-02-24 22:19 UTC
I'm using last build from your Jenkins site. Also I'm using the last version of onebone's EconomyShop. But when I buy an apple or some other food, I can't eat it. I can only eat the food, which was given to me by the /i (EssentialsPE command) | /give - command.  And when I re-join the server, I can eat the bought food. Propably, it's your mistake.

**Comment by MasterWolf** [comment] 2016-02-24 22:20
i think that its plugins issue

**Comment by Shadow166050** [comment] 2016-02-24 22:21
Drop the food then pick back up and your able to eat it

**Comment by thebigsmileXD** [comment] 2016-02-24 22:47
1st this is a duplicate of an very old, closed issue.
2nd it must have to do with addItem. Never got that issue anymore.
I also had EconomyShop.

**Closed by thebigsmileXD** 2016-02-24 22:47 UTC
