### ISSUE TITLE
Crash with Windows 10 edition 0.15

### ISSUE THREAD

**Issue by lcswolf** [ClearSkyTeam/ClearSky#649] opened 2016-08-04 19:06 UTC
Trying to craft a crafting bench on fresh install and server crashes with this files:

[CrashDump_Thu_Aug_4-11.05.13-ACT_2016.txt](https://github.com/ClearSkyTeam/ClearSky/files/402397/CrashDump_Thu_Aug_4-11.05.13-ACT_2016.txt)
[CrashDump_Thu_Aug_4-11.03.46-ACT_2016.txt](https://github.com/ClearSkyTeam/ClearSky/files/402398/CrashDump_Thu_Aug_4-11.03.46-ACT_2016.txt)

**Comment by robske110** [comment] 2016-08-04 19:23
For a real quick soloution use Build #
From http://robskebueba.no-ip.biz/CSphar.htm

**Comment by lcswolf** [comment] 2016-08-04 19:33
Just gave that a try same issue

**Comment by robske110** [comment] 2016-08-04 19:41
can you try to get a proper traceback? If you do not know how, that's fine. All windows 10 issues are estimated to be fixed in about 2 weeks when @dktapps finishes his awesome work on that

**Comment by lcswolf** [comment] 2016-08-04 19:47
Sorry I don't, A bit of a noob when it comes to minecraft pocket servers. If you can point me to the right direction I am happy try it is on a test vps so got nothing to lose on it.

**Comment by Aericio** [comment] 2016-08-05 02:03
@robske110 Since dan doesn't like me making issues, your webserver is still down. I really think you should just host it on some free web hosting just for ClearSky phars.
(I'm sorry for posting this here...)

**Comment by thebigsmileXD** [comment] 2016-08-05 06:37
Actually, what did you try to craft? Fixed this on Log yesterday.
@robske110 i really want json recipies. i am pissed about everything being outdated when mcpe has sth new

**Comment by robske110** [comment] 2016-08-05 07:54
Let's wait some more weeks until @dktapps finishes his awesome inv rewrite. Then I'll implement json recipes

**Comment by lcswolf** [comment] 2016-08-05 08:28
If it helps i tried to craft a crafting table

**Comment by lcswolf** [comment] 2016-08-05 08:30
If it helps i tried to craft a crafting table

**Comment by thebigsmileXD** [comment] 2016-08-05 08:31
Thanks

**Comment by Aericio** [comment] 2016-08-05 08:38
Wait, how much is "some more weeks"?

**Comment by robske110** [comment] 2016-08-05 08:45
> can you try to get a proper traceback? If you do not know how, that's fine. All windows 10 issues are estimated to be fixed in about 2 weeks when @dktapps finishes his awesome work on that

**Comment by robske110** [comment] 2016-08-05 08:45
> If it helps i tried to craft a crafting table 
You crafted a crafting table with a crafting table. Makes not that much sense

**Comment by Aericio** [comment] 2016-08-05 08:46
Wait, how much is "in about 2 weeks"?

**Comment by lcswolf** [comment] 2016-08-05 08:58
@robske110 Not sure where you got crafted a crafting table with a crafting table from all I said was I was trying to craft the crafting table when the server crashed

**Comment by thebigsmileXD** [comment] 2016-08-05 09:15
@lcswolf true. But it seems like it was a crafting table due to the crashdump

**Comment by Aericio** [comment] 2016-08-05 09:15
So you went in your inventory to craft a crafting table to craft more blocks and it crashed when it crafted the crafting table?

**Comment by Aericio** [comment] 2016-08-05 09:23
### ***Debug 2***
```
Notice: Undefined offset: 6 in phar://C:/Users/hello/Desktop/Network/ClearSky.phar/src/pocketmine/Player.php on line 3000
Fatal error: Uncaught TypeError: Argument 2 passed to pocketmine\inventory\ShapedRecipe::setIngredient() must be an instance of pocketmine\item\Item, null given, called in phar://C:/Users/hello/Desktop/Network/ClearSky.phar/src/pocketmine/Player.php on line 3000 and defined in phar://C:/Users/hello/Desktop/Network/ClearSky.phar/src/pocketmine/inventory/ShapedRecipe.php:93
Stack trace:
#0 phar://C:/Users/hello/Desktop/Network/ClearSky.phar/src/pocketmine/Player.php(3000): pocketmine\inventory\ShapedRecipe->setIngredient('g', NULL)
#1 phar://C:/Users/hello/Desktop/Network/ClearSky.phar/src/pocketmine/network/Network.php(218): pocketmine\Player->handleDataPacket(Object(pocketmine\network\protocol\CraftingEventPacket))
#2 phar://C:/Users/hello/Desktop/Network/ClearSky.phar/src/pocketmine/Player.php(2160): pocketmine\network\Network->processBatch(Object(pocketmine\network\protocol\BatchPacket), Object(pocketmine\Player))
#3 phar://C:/Users/hello/Desktop/Network/ClearSky.phar/src/pocketmine/network/RakLi in phar://C:/Users/hello/Desktop/Network/ClearSky.phar/src/pocketmine/inventory/ShapedRecipe.php on line 93
[11:20:20] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[11:20:25] [Server thread/EMERGENCY]: Please upload the "C:\Users\hello\Desktop\Network\crashdumps/CrashDump_Fri_Aug_5-11.20.23-CEST_2016.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
```

**Comment by robske110** [comment] 2016-08-05 09:24
Thanks, @Aerico will fix this today :)

**Comment by lcswolf** [comment] 2016-08-05 09:26
@thebigsmileXD unless it refers to the 2x2 crafting grid

**Comment by Aericio** [comment] 2016-08-05 09:28
It only happens on the 2x2 crafting grid from your Inventory. I just tested the crafting table, it didn't crash and works fine :)

**Comment by robske110** [comment] 2016-08-05 10:04
The debug messages are due to @thebigsmileXD merging a not finished branch.

**Comment by dktapps** [comment] 2016-08-05 11:09
I _said_ you'd regret this :P

**Closed** 2016-08-05 11:09 UTC
Labels: bug, In progress

**Comment by robske110** [comment] 2016-08-05 11:10
fixed now :P And this was not caused by dan's commit. https://github.com/ClearSkyTeam/ClearSky/issues/651 that one was
