### ISSUE TITLE
Says "Server Full" when it isn't full

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#507] opened 2016-06-14 04:40 UTC
I am using PHP7. After I wait a few minutes, I am able to login. I don't have CustomAlert also. Is it just client problem? It doesn't send the join thing to the server console, it just instantly puts it to "Server Full".

**Comment by robske110** [comment] 2016-06-14 04:47
unable to reproduce...
Please give some more info

**Comment by Aericio** [comment] 2016-06-14 05:12
I don't know what else info... thats it.

**Comment by thebigsmileXD** [comment] 2016-06-14 14:09
Which version?

**Comment by Aericio** [comment] 2016-06-14 21:41
PHP7... there isn't a version number on it.

**Comment by robske110** [comment] 2016-06-18 07:44
Closing due to unable to reproduce

**Closed by robske110** 2016-06-18 07:44 UTC
Labels: Not enough info

**Comment by Aericio** [comment] 2016-06-18 08:39
It was kind of gone already, sorry
