### ISSUE TITLE
Offset LightPopulated not found failed

### ISSUE THREAD

**Issue by intagaming** [ClearSkyTeam/ClearSky#640] opened 2016-07-30 05:39 UTC
I loaded by world, teleport to it, and the warnings came.
Warning: assert(): Offset LightPopulated not found failed in phar://D:/Games/PocketMine/ClearSky/ClearSky.phar/src/pocketmine/nbt/tag/CompoundTag.php on line 45
Latest version of ClearSky.

**Comment by robske110** [comment] 2016-07-30 06:31
May be a faulty world

**Comment by intagaming** [comment] 2016-07-30 06:33
Was able to load without problem on Genisys though..

**Comment by robske110** [comment] 2016-07-30 07:10
Could you provide a debug lvl 2 traceback?

**Comment by intagaming** [comment] 2016-07-30 07:19
How can i do that?

**Comment by robske110** [comment] 2016-07-30 07:28
Set debug-level in pocketmine.yml to 2

**Comment by intagaming** [comment] 2016-07-30 07:54
Level 2, the same as Level 1:
Warning: assert(): Offset LightPopulated not found failed in phar://D:/Games/PocketMine/ClearSky/ClearSky.phar/src/pocketmine/nbt/tag/CompoundTag.php on line 45

**Comment by robske110** [comment] 2016-07-30 08:12
Hmmm. Gonna look into this.

**Comment by robske110** [comment] 2016-07-30 10:14
we cannot resolve this unless we get a proper traceback.

**Comment by intagaming** [comment] 2016-07-30 10:16
What about i give you the world ?

**Comment by robske110** [comment] 2016-07-30 10:18
Actually i found out #153 this has already been reported. And we already did something to fix it. https://github.com/ClearSkyTeam/ClearSky/commit/b795a393c35eca57b06b41bfbccef78bdf66dbd1
This looks like a new issue.

**Comment by robske110** [comment] 2016-07-30 10:24
yep, it would be nice if you could give me the world

**Comment by intagaming** [comment] 2016-07-30 10:27
Of course sir, because this is the warning, not the crash.
So sad that github can't unload rar or zip even they say "Try again with a ZIP".
http://www.mediafire.com/download/irvrbgkqcnf0gdw/hl-1-0.zip
Stand right at the spawn point and look at the console.

**Comment by robske110** [comment] 2016-07-30 10:44
Are you sure you are using the latest version? Because i cannot reproduce this.
http://robskebueba.no-ip.biz/CSPhar.php?type=1&branch=php7
get the latest version from there

**Comment by intagaming** [comment] 2016-07-30 10:50
Yes im very sure with the "Fix #630" commit phar.
Here's the video: 
https://sendvid.com/zs8xsfw0

**Comment by robske110** [comment] 2016-07-30 10:55
Well, i don't get this at all. And i was in your world

**Comment by intagaming** [comment] 2016-07-30 10:58
The warnings weren't showed to you? That's strange...

**Comment by robske110** [comment] 2016-07-30 11:11
[12:42:34] [Server thread/INFO]: robske_110[/94.217.175.16:61722] logged in with entity id 1 at (world, 128, 70, 128)
HBNotFound![12:42:36] [Server thread/INFO]: robske_110 ist dem Spiel beigetreten!
[12:42:44] [Server thread/INFO]: Preparing level "hl-1-0"
Server_Core::LevelChange 
[12:42:52] [Server thread/INFO]: [robske_110: Set own game mode to Creative Mode]
[12:45:13] [Server thread/INFO]: robske_110 hat das Spiel verlassen!
[12:45:13] [Server thread/INFO]: robske_110[/94.217.175.16:61722] logged out due to client disconnect

**Comment by intagaming** [comment] 2016-07-30 11:12
Is there any option or php.ini or server.properties i can change ?

**Comment by Aericio** [comment] 2016-07-30 19:26
Are you still using Genisys' server folder? (Like all you did was replace Genisys phar with ClearSky) If you did, make a new one and use ClearSky's installer instead. Put the bin, phar, and start.cmd (Windows) or start.sh (Linux). Run start file and then run the installation.

**Comment by intagaming** [comment] 2016-07-31 01:25
Completely clean ClearSky install with just .phar, CS PHP lib and start.cmd .

**Comment by thebigsmileXD** [comment] 2016-07-31 07:16
True, i did fix this once. Should not appear anymore, i don't have this either

**Comment by robske110** [comment] 2016-07-31 08:49
Closing due to unable to reproduce under very even circumstances.

**Closed by robske110** 2016-07-31 08:49 UTC
Labels: unconfirmed
