### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Touficbatache** [ClearSkyTeam/ClearSky#587] opened 2016-07-08 12:25 UTC
I got an error after setting up PocketMine here is what I got : 

[20:21:55] [Server thread/INFO]: Loading pocketmine.yml...
[20:21:55] [Server thread/INFO]: Loading server properties...
[20:21:55] [Server thread/INFO]: Enable MainLogger to file
[20:21:55] [Server thread/INFO]: Selected English (eng) as the base language
[20:21:55] [Server thread/INFO]: Starting Minecraft: PE server version v0.15.x beta
[20:21:55] [Server thread/INFO]: Starting remote control listener
[20:21:55] [Server thread/INFO]: RCON running on 0.0.0.0:19132
[20:21:55] [Server thread/INFO]: Opening server on 0.0.0.0:19132
[20:21:55] [Server thread/INFO]: This server is running ClearSky version 1.1-php7 "DarkSunset" (API 2.0.0) Build 117
[20:21:55] [Server thread/INFO]: ClearSky is distributed under the LGPL License

Parse error: syntax error, unexpected ')' in phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/src/raklib/protocol/Packet.php on line 71

Fatal error: Exception thrown without a stack frame in Unknown on line 0
[20:21:57] [Server thread/EMERGENCY]: [RakLib Thread #-1264583520] RakLib crashed!
[20:21:57] [Server thread/INFO]: Preparing level "world"
[20:21:57] [Server thread/INFO]: Starting GS4 status listener
[20:21:57] [Server thread/INFO]: Setting query port to 19132
[20:21:57] [Server thread/INFO]: Query running on 0.0.0.0:19132
[20:21:58] [Server thread/INFO]: Default game type: Survival Mode
[20:21:58] [Server thread/INFO]: Done (3.083s)! For help, type "help" or "?"
[20:21:58] [Server thread/CRITICAL]: [Network] Stopped interface pocketmine\network\RakLibInterface due to Call to undefined method raklib\server\RakLibServer::getTerminationInfo()
[20:21:58] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\network\rcon\RCONInstance::isWaiting()" (EXCEPTION) in "/src/pocketmine/network/rcon/RCON" at line 64
[20:21:58] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[20:21:58] [Server thread/EMERGENCY]: Please upload the "/storage/emulated/0/PocketMine/crashdumps/CrashDump_Fri_Jul_8-20.21.58-CST_2016.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
[20:21:58] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\network\rcon\RCONInstance::kill()" (EXCEPTION) in "/src/pocketmine/network/rcon/RCON" at line 54
[20:21:58] [Server thread/EMERGENCY]: Crashed while crashing, killing process
[20:21:58] [Server thread/EMERGENCY]: Error: Call to undefined method pocketmine\network\rcon\RCONInstance::kill()
[PE Server] Server was stopped.

**Comment by robske110** [comment] 2016-07-08 12:32
Duplicate of #585 and please use the src not a phar, currently jenkins is broken

**Closed** 2016-07-08 12:32 UTC
Labels: duplicate

**Comment by Touficbatache** [comment] 2016-07-08 12:36
Ok thanks. Can you just compile the good phar for me because I don't know
how to do so.

**Comment by Touficbatache** [comment] 2016-07-08 12:56
I installed the src but it doesn' work either :

[20:54:30] [Server thread/WARNING]: Non-packaged ClearSky installation detected, do not use on production.
[20:54:31] [Server thread/INFO]: Loading pocketmine.yml...
[20:54:31] [Server thread/INFO]: Loading server properties...
[20:54:31] [Server thread/INFO]: Enable MainLogger to file
[20:54:31] [Server thread/INFO]: Selected English (eng) as the base language
[20:54:31] [Server thread/INFO]: Starting Minecraft: PE server version v0.15.x beta
[20:54:31] [Server thread/INFO]: Starting remote control listener
[20:54:31] [Server thread/INFO]: RCON running on 0.0.0.0:19132
[20:54:31] [Server thread/INFO]: Opening server on 0.0.0.0:19132
[20:54:31] [Server thread/INFO]: This server is running ClearSky version 1.1-php7 "DarkSunset" (API 2.0.0) Build CuttingEdge
[20:54:31] [Server thread/INFO]: ClearSky is distributed under the LGPL License
[20:54:32] [Server thread/WARNING]: ----- ClearSky Auto Updater -----
[20:54:33] [Server thread/WARNING]: It appears you're running a CuttingEdge build, it means you are using src or a custom build
[20:54:33] [Server thread/WARNING]: If you want to run a production server, please use a phar provided by our Jenkins server for better performance
[20:54:33] [Server thread/WARNING]: If you are running a custom build, please remember that the ClearSky Team won't support this version
[20:54:33] [Server thread/WARNING]: ----- -------------------------- -----
[20:54:33] [Server thread/INFO]: Preparing level "world"
[20:54:34] [Server thread/INFO]: Starting GS4 status listener
[20:54:34] [Server thread/INFO]: Setting query port to 19132
[20:54:34] [Server thread/INFO]: Query running on 0.0.0.0:19132
[20:54:34] [Server thread/INFO]: Default game type: Survival Mode
[20:54:34] [Server thread/INFO]: Done (3.302s)! For help, type "help" or "?"
[20:54:34] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\network\rcon\RCONInstance::isWaiting()" (EXCEPTION) in "/src/pocketmine/network/rcon/RCON" at line 64
[20:54:34] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[20:54:34] [Server thread/EMERGENCY]: Please upload the "/storage/emulated/0/PocketMine/crashdumps/CrashDump_Fri_Jul_8-20.54.34-CST_2016.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
[20:54:34] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\network\rcon\RCONInstance::kill()" (EXCEPTION) in "/src/pocketmine/network/rcon/RCON" at line 54
[20:54:34] [Server thread/EMERGENCY]: Crashed while crashing, killing process
[20:54:34] [Server thread/EMERGENCY]: Error: Call to undefined method pocketmine\network\rcon\RCONInstance::kill()
[PE Server] Server was stopped.

**Comment by robske110** [comment] 2016-07-08 14:13
This is not the current src

**Comment by Touficbatache** [comment] 2016-07-08 14:14
Yes it is... Which one is the current ? Link plz.

**Comment by robske110** [comment] 2016-07-08 14:21
https://github.com/ClearSkyTeam/ClearSky/archive/php7.zip

**Comment by Touficbatache** [comment] 2016-07-08 14:21
Thanks
