### ISSUE TITLE
furnace crash

### ISSUE THREAD

**Issue by Tolo0** [ClearSkyTeam/ClearSky#115] opened 2016-02-07 23:03 UTC
When touching a furnace. Players crash.

**Comment by thebigsmileXD** [comment] 2016-02-07 23:06
Are you sure? That was fixed in the beginnings of ImagicalMine, they havent changed in ClearSky since that..

**Comment by Tolo0** [comment] 2016-02-07 23:20
I'm using thethe latest build. Had to compress it to post.
[Furnace.mp4.zip](https://github.com/ClearSkyTeam/ClearSky/files/120985/Furnace.mp4.zip)

**Comment by NML32** [comment] 2016-02-07 23:28
you should do /version in the video next time.

**Comment by Tolo0** [comment] 2016-02-07 23:52
![screenshot_2016-02-07-23-51-36](https://cloud.githubusercontent.com/assets/13458191/12876248/d6b084a8-cdf5-11e5-94cd-e2770a0e628f.png)

**Comment by nonbe102** [comment] 2016-02-08 02:47
Can the dev see your crashdump? this might be caused by a plugin.

**Comment by TheKillerTacos** [comment] 2016-02-08 02:50
Its a crash from the client not from the server nonbe.. So there is no crash dump

**Comment by Tolo0** [comment] 2016-02-08 08:25
Nope. No crash dumb

**Comment by thebigsmileXD** [comment] 2016-02-09 14:49
No such problem for me on the latest build

**Comment by Tolo0** [comment] 2016-02-09 16:09
I also crash when touching leaves sometimes.

**Comment by TheKillerTacos** [comment] 2016-02-09 19:34
it might be the MC:PE Version, if its updated (0.13.1/2)

**Comment by thebigsmileXD** [comment] 2016-02-09 22:22
Touching leaves and sprinting on leaves. Spawning leaf breaking particles will also crash you. Only if theres a transparent bit in a particle i reported it already as a bug to mojang

**Comment by robske110** [comment] 2016-02-12 10:58
Client Bug (wont fix)

**Comment by thebigsmileXD** [comment] 2016-02-15 00:59
Actually.. i am not so sure anymore, if its a client bug. I think the leaves particles are sent by the server.

**Comment by Efforto** [comment] 2016-02-15 16:21
Ehh...Genisys and Nukkit has already fix this bug......

**Comment by thebigsmileXD** [comment] 2016-02-15 16:23
Nice for them

**Comment by aodzip** [comment] 2016-02-16 03:42
ImagicalMine have fix this years ago , and I cant get this bug

**Closed** 2016-02-16 09:38 UTC
Labels: bug, wontfix
