### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#723] opened 2016-09-18 23:06 UTC
![image](https://cloud.githubusercontent.com/assets/16523741/18619812/6be93e6a-7da1-11e6-87d3-ce4481da1567.png)

**Comment by robske110** [comment] 2016-09-19 12:20
weird exception up there (line 38 is nothing, just a TAB)

**Comment by robske110** [comment] 2016-09-19 12:46
can you confirm this on the latest build?

**Comment by Aericio** [comment] 2016-09-20 02:12
Latest.

**Comment by kam187** [comment] 2016-09-22 14:24
You should extract the phar and check the file.

There's plenty of online phar extractors.  It's possible that file had a typo in some commit or something and it's not totally latest.

**Comment by robske110** [comment] 2016-09-26 05:36
Closing due to unable to reproduce, aerico try to redownload the phar

**Closed** 2016-09-26 05:36 UTC

**Comment by Aericio** [comment] 2016-09-26 06:10
Site down

**Comment by robske110** [comment] 2016-09-26 11:50
MacOSX (fuck you apple) booted in safe mode after it crashed yesterday. That's what i call a fail.

**Comment by thebigsmileXD** [comment] 2016-09-26 12:55
He uses Apple, thats the error 😆

**Comment by robske110** [comment] 2016-09-26 12:57
:D
