### ISSUE TITLE
Alias of disabled plugin does not give error

### ISSUE THREAD

**Issue by thebigsmileXD** [ClearSkyTeam/ClearSky#494] opened 2016-06-11 10:03 UTC
I dont get command not found neither any error

**Comment by robske110** [comment] 2016-06-11 13:16
may be related to aliases not realy deleted correctly at all

**Comment by thebigsmileXD** [comment] 2016-06-11 15:31
May be related to the mess @MCPEPIG did in his commit.

**Comment by MCPEPIG** [comment] 2016-06-11 16:01
You really have to blame everything on me? Also, I didn't mess with anything alias related.

**Comment by SalmonGER** [comment] 2016-06-11 17:42
@robske110 Wait, does the alias feature in the pocketmine.yml get deleted?

**Comment by robske110** [comment] 2016-06-11 18:21
what?

**Comment by SalmonGER** [comment] 2016-06-11 18:28
@robske110 This **alias:** thing at the bottom of the pocketmine.yml file

**Comment by robske110** [comment] 2016-06-11 18:35
will not be removed, why should it be?

**Comment by MCPEPIG** [comment] 2016-06-12 04:55
This is code to register aliases:
`public function registerServerAliases(){
		$values = $this->server->getCommandAliases();
		foreach($values as $alias => $commandStrings){
			if(strpos($alias, ":") !== false or strpos($alias, " ") !== false){
				$this->server->getLogger()->warning($this->server->getLanguage()->translateString("pocketmine.command.alias.illegal", [$alias]));
				continue;
			}
			$targets = [];
			$bad = "";
			foreach($commandStrings as $commandString){
				$args = explode(" ", $commandString);
				$command = $this->getCommand($args[0]);
				if($command === null){
					if(strlen($bad) > 0){
						$bad .= ", ";
					}
					$bad .= $commandString;
				}else{
					$targets[] = $commandString;
				}
			}
			if(strlen($bad) > 0){
				$this->server->getLogger()->warning($this->server->getLanguage()->translateString("pocketmine.command.alias.notFound", [$alias, $bad]));
				continue;
			}
			//These registered commands have absolute priority
			if(count($targets) > 0){
				$this->knownCommands[strtolower($alias)] = new FormattedCommandAlias(strtolower($alias), $targets);
			}else{
				unset($this->knownCommands[strtolower($alias)]);
			}
		}
	}
`
I think the problem is when a plugin disables, it doesn't unset the alias from SimpleCommandMap::$knownCommands

**Comment by thebigsmileXD** [comment] 2016-06-12 09:49
@MCPEPIG You made a pr for alias, dont you remember?

**Comment by MCPEPIG** [comment] 2016-06-12 18:12
It was never merged.

**Comment by thebigsmileXD** [comment] 2016-06-12 18:14
Can you tell me how unregister didnt work before?

**Comment by MCPEPIG** [comment] 2016-06-12 19:30
When the function was called, the command didn't unregister.

**Closed** 2016-11-01 15:51 UTC
Labels: bug
